language: python

python: 3.4

addons:
  postgresql: 9.3

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres@localhost/kuulemma_test

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install -r requirements-dev.txt
  - npm -g install npm@2.1.1
  - npm install
  - bower install

before_script:
  - psql -c 'create database kuulemma_test;' -U postgres

script:
  - isort --recursive --diff kuulemma tests && isort --recursive --check-only kuulemma tests
  - flake8 .
  - gulp jshint
  - py.test
  - gulp test-karma
  - gulp test-protractor
